site_name: "CMU 17-313: Foundations of Software Engineering"

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/17313_numberbox.png
  favicon: assets/favicon.ico
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - announce.dismiss

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      title: On This Page
      toc_depth: 3
      permalink: true

extra_css:
  - stylesheets/custom.css

plugins:
  - search
  - markdownextradata

nav:
  - Home: index.md
  - Course Overview: overview.md
  - Syllabus: syllabus.md
  - Projects:
      # projects/index.md # Dummy home page; remove once we start adding homework below
      - "Project 1: Hello, NodeBB!":
          - projects/P1/index.md
          - 1A Build Checkpoint: projects/P1/1_checkpoint.md
          - 1B Starter Task: projects/P1/2_refactoring.md
          - Development Tools Guide: projects/P1/development-tools-guide.md
          - Git Commands Reference: projects/P1/git-commands-reference.md
          - Resources and Documentation: projects/P1/documentation.md
          - FAQ: projects/P1/faq.md
      - "Project 2: Collaborative Development":
          - projects/P2/index.md
          - 2A Team Process & Planning: projects/P2/1_teamprocess.md
          - 2B First Sprint: projects/P2/2_firstsprint.md
          - 2C Second Sprint: projects/P2/3_secondsprint.md
      # - "Project 3: Continuous Integration + Deployment":
      #     - projects/P3/index.md
      #     - "Linux VM Deployment Instructions": projects/P3/deployment.md
      # - "Project 4: Architecting an LLM Integration":
      #     - projects/P4/index.md
      #     - 4A Design and Test: projects/P4/1_checkpoint.md
      #     - 4B Implementation and Evaluation: projects/P4/2_checkpoint.md
      # - "Project 5: Open Source Excursion":
      #     - projects/P5/index.md
      #     - "5A Project and Task Selection": projects/P5/1_projectcheck.md
      #     - "5B & C Project Presentations, Final Report, and Reflections": projects/P5/2_projectfinal.md

  - Recitations:
      # - recitations/index.md # Dummy home page; remove once we start adding recitations below
      # S26 RECIS
      - Recitation 1 - Understand NodeBB: recitations/reci1-nodeBB.md
      - Recitation 2 - Team Contract Workshop: recitations/reci2-teamcontract.md
      - Recitation 3 - Software Archaeology: recitations/reci3-archaeology.md
      - Recitation 4 - Checkpoint Presentations: recitations/reci4-checkpoint.md
      - Recitation 5 - Team Dysfunction: recitations/reci5-team-dysfunction.md

      # F25 RECIS
      # - Recitation 2 - Team Contract Workshop: recitations/reci2-teamcontract.md
      # - Recitation 3 - Software Archaeology: recitations/reci3-archaeology.md
      # - Recitation 4 - Checkpoint Presentations: recitations/reci4-checkpoint.md
      # - Recitation 5 - Team Dysfunction: recitations/reci5-team-dysfunction.md
      # - Recitation 6 - Deployment: recitations/reci6-deployment.md
      # - Recitation 7 - On Prem Deployment: recitations/reci7-onprem-setup.md
      # - Recitation 8 - Docker and Containerization: recitations/reci8-docker.md
      # - Recitation 9 - Property-Based Testing: recitations/reci9-pbt.md
      # - Recitation 10 - Open Source Scavenger Hunt: recitations/reci10-open-source.md
      # - Recitation 11 - Open Source Project and Task Selection Check In: recitations/reci11-p5-checkin.md

      # OLDER RECIS
      # - Recitation 8 - LLMs: recitations/reci8-llms.md
      # - Recitation 9 - Open Source Scavenger Hunt: recitations/reci10-open-source.md
      # - Recitation 10 - Team Feedback: recitations/reci10-team-feedback.md
      # - Recitation 13 - Open Source Projects Presentation: recitations/reci13-open-source-presentation.md
      # - Recitation 7 - Azure Setup: recitations/reci7-azure-setup.md
      # - Recitation 9 - Team Feedback: recitations/reci9-team-feedback.md
      # # - Recitation 10 - Team Feedback: recitations/reci10-team-feedback.md
      # # - Recitation 8 - Team Feedback: recitations/reci8-team-feedback.md
      # # - Recitation 9 - Machine Learning: recitations/reci9-ml.md
      # # - Recitation 10 - Open Source Projects: recitations/reci10-open-source.md
      # - Recitation 11 - Midterm Review: recitations/reci11-midterm-review.md
  - Hall of Fame: hall-of-fame.md
  - Resources:
      - Development Tools Guide: projects/P1/development-tools-guide.md
      - Git Commands Reference: projects/P1/git-commands-reference.md
      - Resources and Documentation: projects/P1/documentation.md
      - GitHub Guide: projects/P1/github.md
      - Extra Resources: extra_resources.md
  - Canvas: https://canvas.cmu.edu/courses/51340 # TODO: need to update Canvas Link
  - Gradescope: https://www.gradescope.com/courses/1213157 # TODO: need to update Gradescope link
  - Slack: https://join.slack.com/t/cmu-313-s26/shared_invite/zt-3lm0t5j8k-kriwFq_6SZDHEcSV1c2PSg

